### ISSUE TITLE
Swift 3 errors

### ISSUE THREAD

**Issue by TanelTeemusk** [AugustRush/Stellar#12]
I love Stellar. Animations with Swift like they should be. Thanks.
but...
Swift 3 branch seems to throw compile errors. Any plans on fixing this? Swift 3 officially out today.
thanks.

**Comment by AugustRush** [comment]
I will rewrite for Swift 3, it should take some time to do this.

**Comment by franobarrio** [comment]
@AugustRush You rock ! This animation framework is the best !! 
I'll wait for Swift 3 version :)
Cheers

**Comment by AugustRush** [comment]
Thanks!  
Cheers  :)
