### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by Krisiacik** [AugustRush/Stellar#14]
Hi,

I am using the library with solid success. However I am a bit stressed by the stale development lately. What are your plans honestly?

**Comment by AugustRush** [comment]
What did you mean？My english is a little poor ：）

**Comment by Krisiacik** [comment]
You seem to be not maintaining the project.

**Comment by TanelTeemusk** [comment]
I'm using it for some of my projects as well. Thank you for a great animation library. I've tested many and Stellar seems to be the best. 
I'm also a bit concerned about the slowness of upgrading to swift 3

ps. Maybe you should add the 'donate' button to readme to get the motivation up ;)

**Comment by AugustRush** [comment]
The tag 0.65 will work fine at Swift 3.0.
