### ISSUE TITLE
How to "glue" animation

### ISSUE THREAD

**Issue by ghost** [AugustRush/Stellar#19]
I want to design an animation by chaining several animations in a programmatically way.

I tried the following without success:
```
aView = aView.moveX(5.0).duration(2.0).completion({ do_something() }).then()
...
aView = aView.moveX(7.0).duration(1.0).completion({ do_something() }).then()

aView.animate()
```
 How to achieve this?

**Comment by AugustRush** [comment]
aView.moveX(5.0).duration(2.0).completion {
                do_something()
            }.then().moveX(7.0).duration(1).completion {
                do_something()
        }.animate()

**Comment by ghost** [comment]
Thanks. But the need is to create an animation step by step. So in your example the `then` statement is added later on the code.

```` swift

aView.moveX(5.0).duration(2.0).completion {
do_something()
}

// later...
aView.then().moveX(7.0).duration(1).completion {
do_something()
}

// later...
aView.animate()
````

**Comment by AugustRush** [comment]
Yes, it is.

**Comment by ghost** [comment]
Hum... There is something weird.

So code is:

```` swift
_ = aView
    .moveX(5.0)
    .duration(2.0)
    .completion {
          do_something()
    }
    .then

// later...
_ = aView
    .moveX(7.0)
    .duration(1)
    .completion {
          do_something()
    }
    .then

// and at last

aView
.completion { do_something }
.animate

````

Last completion do not occur. Let's try by adding a `delay`. So the last part of code is now:

```` swift
aView
.delay (0.01)
.completion { do_something }
.animate
````

Last completion still not occur. But replacing delay by an animation, like `rotate` make it work!
```` swift
aView
.rotate (0.01)
.completion { do_something }
.animate
````

**Comment by AugustRush** [comment]
only 'delay' can not make an animation...

**Comment by ghost** [comment]
I solved this by moving `then` to the top. So:

```` swift
_ = aView
    .then
    .moveX(5.0)
    .duration(2.0)
    .completion {
          do_something()
    }
    

// later...
_ = aView
    .then
    .moveX(7.0)
    .duration(1)
    .completion {
          do_something()
    }

// and at last

aView
.completion { do_something }
.animate

````
