### ISSUE TITLE
makeAlpha calls are crashing

### ISSUE THREAD

**Issue by TanelTeemusk** [AugustRush/Stellar#20]
Updated via cocoapods and makeAlpha calls fail with 
fatal error: Should not be excute forever!

**Comment by AugustRush** [comment]
You can try it again, i had update podspec's version to 0.66 just now.

**Comment by TanelTeemusk** [comment]
Managed to make it work again with the following pod:
`pod 'Stellar', :tag => '0.65', :git => 'https://github.com/AugustRush/Stellar'`

I'll try to remove tag and try again now.

**Comment by TanelTeemusk** [comment]
Ok, yup. seems to be a bug on 0.66 with makeAlpha. When I update without a tag and see that it's using 0.66 it crashes the same fatal error.

**Comment by AugustRush** [comment]
Yes, it's a error of code, i  have fixed it.

**Comment by TanelTeemusk** [comment]
still crashing when calling makeAlpha

**Comment by AugustRush** [comment]
sorry , you can check this commit https://github.com/AugustRush/Stellar/commit/7b1c9e5380d4c14e46755611d3794b10c273d504
