### ISSUE TITLE
Infinity repeatCount.

### ISSUE THREAD

**Issue by Anatoli4** [AugustRush/Stellar#23]
How i can simulate infinity repeat count?
repeatCount(Int.max)?

**Comment by AugustRush** [comment]
Yes, you can do it like this, it's enough.

**Comment by Anatoli4** [comment]
repeatCount(Int.max)
This way don't work correctly, animation play ~1 minute and stop.

**Comment by AugustRush** [comment]
Yes, this is a bug, may be have relationship with runloop? i will find it.

**Comment by AugustRush** [comment]
@Anatoli4 I have fixed this issue，due to the UIPushBehavior's mode , i have changed it to 'continuous'. you can check the last commit.
