### ISSUE TITLE
Migrate Examples to Newest Swift/Xcode version

### ISSUE THREAD

**Issue by gkaimakas** [AugustRush/Stellar#27]
Hello,

As is, the examples do not support Xcode 9.  Can they be updated to support Xcode 9 and at least Swift 3?

**Comment by AugustRush** [comment]
Can you elaborate on your problem?

发自我的 iPhone

**Comment by gkaimakas** [comment]
I could not build the examples in Xcode 9 because they use Swift 2.x.
