### ISSUE TITLE
Unable into install via CocoaPods

### ISSUE THREAD

**Issue by gkye** [AugustRush/Stellar#3]
I've noticed there's a `podspec` file available but some for strange reason I can't find the repo on CocoaPods.

``` ruby
pod 'Stellar'
```

Returns a `Unable to find a specification for Stellar` error.

Although downloading straight from the source works.

``` ruby
pod 'Stellar', :git=>'https://github.com/AugustRush/Stellar.git'
```

**Comment by AugustRush** [comment]
I have pushed my podspec to CocoaPods , now you can fint it through 'pod search Stellar'.
![2ad30049-4e46-4329-8058-7c644dd13d7e](https://cloud.githubusercontent.com/assets/6881916/15881052/73591242-2d65-11e6-9913-2613e52d8d4c.png)
