### ISSUE TITLE
When I use OC, import the swift code, found that there is no easing and other methods

### ISSUE THREAD

**Issue by HellojingQiu** [AugustRush/Stellar#7]

@interface CALayer (SWIFT_EXTENSION(Stellar))
@end

@interface UIColor (SWIFT_EXTENSION(Stellar))
- (void)fallTo:(UIColor \* _Nonnull)to magnitude:(double)magnitude render:(void (^ _Nonnull)(UIColor \* _Nonnull))render completion:(void (^ _Nullable)(void))completion;
- (void)snapTo:(UIColor \* _Nonnull)to damping:(CGFloat)damping render:(void (^ _Nonnull)(UIColor \* _Nonnull))render completion:(void (^ _Nullable)(void))completion;
- (void)attachmentTo:(UIColor \* _Nonnull)to damping:(CGFloat)damping frequency:(CGFloat)frequency render:(void (^ _Nonnull)(UIColor \* _Nonnull))render completion:(void (^ _Nullable)(void))completion;
- (void)pushedTo:(UIColor \* _Nonnull)to render:(void (^ _Nonnull)(UIColor \* _Nonnull))render completion:(void (^ _Nullable)(void))completion;
  @end

@interface UIDynamicBehavior (SWIFT_EXTENSION(Stellar))
@end

@class UIView;

@interface UILabel (SWIFT_EXTENSION(Stellar))
- (UIView \* _Nonnull)makeTextColor:(UIColor \* _Nonnull)color;
  @end

@interface UITextView (SWIFT_EXTENSION(Stellar))
- (UIView \* _Nonnull)makeTextColor:(UIColor \* _Nonnull)color;
  @end

@interface UIView (SWIFT_EXTENSION(Stellar))
- (BOOL)configureWithJSON:(NSString \* _Nonnull)str error:(NSError \* _Nullable \* _Null_unspecified)error;
  @end

@interface UIView (SWIFT_EXTENSION(Stellar))
- (UIView \* _Nonnull)moveX:(CGFloat)increment;
- (UIView \* _Nonnull)moveY:(CGFloat)increment;
- (UIView \* _Nonnull)moveTo:(CGPoint)point;
- (UIView \* _Nonnull)makeColor:(UIColor \* _Nonnull)color;
- (UIView \* _Nonnull)makeAlpha:(CGFloat)alpha;
- (UIView \* _Nonnull)rotate:(CGFloat)z;
- (UIView \* _Nonnull)rotateX:(CGFloat)x;
- (UIView \* _Nonnull)rotateY:(CGFloat)y;
- (UIView \* _Nonnull)rotateXY:(CGFloat)xy;
- (UIView \* _Nonnull)makeWidth:(CGFloat)width;
- (UIView \* _Nonnull)makeHeight:(CGFloat)height;
- (UIView \* _Nonnull)makeSize:(CGSize)size;
- (UIView \* _Nonnull)makeFrame:(CGRect)frame;
- (UIView \* _Nonnull)makeBounds:(CGRect)bounds;
- (UIView \* _Nonnull)scaleX:(CGFloat)x;
- (UIView \* _Nonnull)scaleY:(CGFloat)y;
- (UIView \* _Nonnull)scaleXY:(CGFloat)x :(CGFloat)y;
- (UIView \* _Nonnull)cornerRadius:(CGFloat)radius;
- (UIView \* _Nonnull)borderWidth:(CGFloat)width;
- (UIView \* _Nonnull)shadowRadius:(CGFloat)radius;
- (UIView \* _Nonnull)zPosition:(CGFloat)position;
- (UIView \* _Nonnull)anchorPoint:(CGPoint)point;
- (UIView \* _Nonnull)anchorPointZ:(CGFloat)z;
- (UIView \* _Nonnull)shadowOffset:(CGSize)offset;
- (UIView \* _Nonnull)shadowColor:(UIColor \* _Nonnull)color;
- (UIView \* _Nonnull)shadowOpacity:(float)opacity;
- (UIView \* _Nonnull)makeTintColor:(UIColor \* _Nonnull)color;
- (UIView \* _Nonnull)completion:(void (^ _Nonnull)(void))c;
- (UIView \* _Nonnull)then;
- (UIView \* _Nonnull)then;
- (void)animate;
- (void)cancelAllRemaining;
  @end

**Comment by AugustRush** [comment]
Maybe i should create bridge for objective-c. Currently，it's only support swift.

**Comment by HellojingQiu** [comment]
Thank you for your reply, and hope that the project is more and more perfect.
